server.servlet.encoding.force-response: true
debug: false
# true??? spring boot?? debug??? ?? ????
management.endpoints.web.exposure.include: "*"
# actuator?? ?? ? ????
#한글
logging:
  level:
    com.fastcampus.projectboard: debug  #? ?? ????? ??? ??? debug level? ???.
    org.springframework.web.servlet: debug  # debug:true? ????. debug:false?? ?? ?? ????? reqeust response debug? ?? ??
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    #jpa??? query log? debug? ???? ??. binding parameter? ?? ?? ????? ?? ???? ???. 
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: hhk
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true #test? database? ?????. resource? file? ???? data.sql? ?? (??? ?????)
    hibernate.ddl-auto: create  # ddl ? ???? ?? domain ?? ??? table??????.
    show-sql: true  #sql?? ???? query???? debug???? ????
    properties: # jpa ???? hibernate ORM? ??. spring? highernate?? ????? ????? ?? ?? ?????? ???? ?? ??
                # ???, ?????? ?? ??
        hibernate.format_sql: true  #?????? ???? ????? ???
        hibernate.default_batch_fetch_size: 100 # jpa?? ???? query? ??? bulk ? select???? ???
  h2.console.enabled: true #in-memory database? h2? ?????, h2 console??? web console????? ?? false? ? ??. ??? true
  sql.init.mode: always # embedded? test???, always? ??, never? ????.

--- # .yaml??? ---? ???? ???? document? ?????.

#spring: #??? spring profile document? ?? ??? ?? ---??. h2 database
#    config.activate.on-profile: testdb  #test db? activate?? ?? ? ? ??? ???? ??
#    datasource:
#      url: jdbc:h2:mem:board;mode=mysql
#      driverClassName: org.h2.Driver
#    sql.init.mode: always
#    test.database.replace: none

#    datasource:
#     url: jdbc:h2:mem:testdb
#      driverClassName: org.h2.Driver
#      username: sa
#      password:
#    sql.init.mode: always
#    test.database.replace: none
