#server.servlet.encoding.force-response: true
debug: false
# the amount of debugs are too huge
management.endpoints.web.exposure.include: "*"
# we see all functions using actuator
logging:
  level:
    com.fastcampus.projectboard: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
# we are able to see query log if we use the BasicBinder

# the below are data which intellij have in accessing to the db
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: wernerk
    password: k#test@1324aabc
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:h2:mem:testdb
#    username: sa
#    driver-class-name: org.h2.Driver

  jpa:
    defer-datasource-initialization: true  # make it possible to create database for test
    hibernate.ddl-auto: create # this helps to create tables just referring to the domains
    show-sql: true # showing sql in debugs
    properties:
      hibernate.format_sql: true # this helps to see the debugs written in a line by several lines. we cannot use all the properties of  hibernate orm. This is the part to include specific features of highernate orm.
      hibernate.default_batch_fetch_size: 100

#  h2.console.enabled: true  #localhost:8080/h2-console작동여부
#  h2.console.enabled: false # default는 false
  sql.init.mode: always # 실제 db를 쓰더라도, data.sql이 반영되도록함.
  data.rest:
    base-path: /api
    detection-strategy: annotated


---

spring:
  config:
    activate:
      on-profile: testdb
  datasource:
    url: jdbc:h2:mem:testdb;mode=mysql # board라는 이름은 중요하지 않음. mode가 mysql모드로 활성화
    username: sa
    password: 1234
    driverClassName: org.h2.Driver

  jpa:
    defer-datasource-initialization: true  # make it possible to create database for test
    hibernate.ddl-auto: create # this helps to create tables just referring to the domains
    show-sql: true # showing sql in debugs
    properties:
      hibernate.format_sql: true # this helps to see the debugs written in a line by several lines. we cannot use all the properties of  hibernate orm. This is the part to include specific features of highernate orm.
      hibernate.default_batch_fetch_size: 100
  h2.console.enabled: true
  sql.init.mode: always
  test.database.replace: none #db를 h2가 임의로 띄우는것이 아닌 내가 정한 testdb라는 걸로 띄우도록 해줌.

